esphome:
  project:
    name: flobs.baresp
    version: 1.0.0

esp8266:
  board: esp01_1m

packages:
  device_base: !include device-base.yaml
  network_services: !include network-services.yaml

  adxl: !include baresp/adxl.yaml
  scanner: !include baresp/scanner.yaml
  baresp: !include baresp/baresp.yaml
