esphome:
  project:
    name: flobs.bettervita-kettle
    version: 1.3.0

packages:
  device_base: !include device-base.yaml
  network_services: !include network-services.yaml
  bettervita_sensors: !include bettervita-kettle/bettervita-kettle-sensors.yaml
  bettervita_ble: !include bettervita-kettle/bettervita-kettle-ble.yaml
  bettervita_button: !include bettervita-kettle/bettervita-kettle-button.yaml
  bettervita_tilt: !include bettervita-kettle/bettervita-kettle-tilt.yaml

esp32:
  board: esp32dev

