interval:
  - interval: 100ms
    then:
      - switch.turn_on: ntc_vcc
      - component.update: ntc_adc
      - switch.turn_off: ntc_vcc

sensor:
  - platform: adc
    id: ntc_adc
    pin: GPIO34
    attenuation: auto
    update_interval: never

  - platform: resistance
    id: ntc_res
    name: "${name_verbose} NTC Resistance"
    sensor: ntc_adc
    configuration: DOWNSTREAM
    resistor: 330kOhm
    filters:
      - median:
          window_size: 7
          send_every: 5
          send_first_at: 3

  - platform: ntc
    id: water_temperature
    name: "${name_verbose} Kettle Temperature"
    sensor: ntc_res
    calibration:
      - 7.675 kOhm -> 96.4째C
      - 101.5kOhm -> 23.0째C
      - 275.0kOhm -> 2.5째C
    unit_of_measurement: "째C"
    device_class: "temperature"

  - platform: adc
    id: battery_voltage
    name: "${name_verbose} Battery Voltage"
    pin: GPIO33
    attenuation: 11db
    update_interval: 60s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.85600 -> 3.8
    on_value:
      then:
        - sensor.template.publish:
            id: battery_level
            state: !lambda |-
              if (x >= 4.2) {
                return 100.0;
              } else if (x < 4.2 && x > 3.4) {
                return 100.0 - ((4.2 - x) / 0.8 * 100.0);
              } else {
                return 0.0;
              }
    unit_of_measurement: "V"
    device_class: "voltage"

  - platform: template
    id: battery_level
    name: "${name_verbose} Battery Level"
    update_interval: never
    unit_of_measurement: "%"
    device_class: "battery"


switch:
  - platform: gpio
    id: ntc_vcc
    pin: GPIO26

binary_sensor:
  - platform: gpio
    id: kettle_in_base
    name: "${name_verbose} Docked"
    device_class: plug
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
      inverted: false
