esphome:
  project:
    name: flobs.bettervita
    version: 1.1.0

packages:
  device_base: !include device-base.yaml
  network_services: !include network-services-esp-idf.yaml
  bettervita_ble: !include bettervita-base/bettervita-base-ble.yaml
  bettervita_led: !include bettervita-base/bettervita-base-led.yaml
  bettervita_pid: !include bettervita-base/bettervita-base-pid.yaml
  bettervita_buttons: !include bettervita-base/bettervita-base-buttons.yaml
  bettervita_display: !include bettervita-base/bettervita-base-display.yaml
  bettervita_profiles: !include bettervita-base/bettervita-base-profiles.yaml
  bettervita_timer: !include bettervita-base/bettervita-base-timer.yaml
  bettervita_rtttl: !include bettervita-base/bettervita-base-rtttl.yaml

esp32:
  board: esp32dev
  framework:
    type: esp-idf

