esphome:
  project:
    name: flobs.eufy30
    version: 1.1.0

esp8266:
  board: esp01_1m

packages:
  device_base: !include device-base.yaml
  network: !include network-services.yaml

  remote: !include eufy30/remote.yaml
  battery: !include eufy30/battery.yaml
  station: !include eufy30/station.yaml

