esphome:
  project:
    name: flobs.thermal_printer
    version: 1.0.0

esp8266:
  board: esp01

packages:
  device_base: !include device-base.yaml
  network_services: !include network-services.yaml

logger:
  hardware_uart: UART1

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
  uart_id: printer_uart
  port: 9847

uart:
  - id: printer_uart
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3

binary_sensor:
  - platform: stream_server
    connected:
      name: Connected
