esphome:
  project:
    name: flobs.vindriktning
    version: 1.0.0

packages:
  hardware_base: !include vindriktning/hardware-base.yaml
  network_services: !include network-services-esp-idf.yaml

  hardware_sensors: !include vindriktning/hardware-sensors.yaml
  hardware_leds: !include vindriktning/hardware-leds.yaml
  hardware_fan: !include vindriktning/hardware-fan.yaml
  config_services_misc: !include vindriktning/configuration-services-misc.yaml
  measurement: !include vindriktning/measurement.yaml
  alert: !include vindriktning/alert.yaml
