esphome:
  platformio_options:
    extra_scripts:
      - pre:../../../packages/xiaomi-ir/pre_extra_script.py

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_MBEDTLS_CERTIFICATE_BUNDLE: n
    advanced:
      ignore_efuse_mac_crc: true

packages:
  device_base: !include device-base.yaml
  network_services: !include network-services-esp-idf.yaml

status_led:
  pin:
    number: GPIO23
    inverted: true

output:
  - platform: gpio
    id: indicator
    pin:
      number: GPIO18
      inverted: true

binary_sensor:
  - platform: gpio
    id: gpio0
    pin:
      number: GPIO0
      inverted: true

remote_receiver:
  pin:
    number: GPIO27
    inverted: true
  dump:
    - nec
    - samsung
    - raw

remote_transmitter:
  pin:
    number: GPIO26
    inverted: false
  carrier_duty_percent: 50%

