switch:
  - platform: gpio
    id: scanner_enable
    pin:
      number: GPIO13

logger:
  hardware_uart: UART1

uart:
  - id: scanner_uart
    baud_rate: 115200
    tx_pin: GPIO1
    rx_pin: GPIO3

esphome:
  includes:
    - "packages/baresp/BarcodeUART.h"

custom_component:
  - lambda: |-
      auto barcode_uart = new BarcodeUART(id(scanner_uart));
      return {barcode_uart};
    components:
      - id: barcode_uart

text_sensor:
  - platform: custom
    lambda: |-
      return {static_cast<BarcodeUART *>(id(barcode_uart))->barcode};
    text_sensors:
      - name: "Barcode"
        id: barcode
