esphome:
  project:
    name: flobs.vindriktning
    version: 1.0.0

packages:
  hardware_base: !include hardware-base.yaml
  network_services: !include ../network-services-esp-idf.yaml

  hardware_sensors: !include hardware-sensors.yaml
  hardware_leds: !include hardware-leds.yaml
  hardware_fan: !include hardware-fan.yaml
  config_services_misc: !include configuration-services-misc.yaml
  measurement: !include measurement.yaml
