substitutions:
  pin_output_led_hold: GPIO17
  pin_led_onoff: GPIO16

output:
  - platform: gpio
    id: output_led_hold
    pin: ${pin_output_led_hold}

light:
  - platform: status_led
    id: led_onoff
    pin: ${pin_led_onoff}

  - platform: binary
    id: led_hold
    output: output_led_hold

