binary_sensor:
  - platform: template
    id: button_onoff
    on_click:
      lambda: |-
        bool is_kettle_mode_active = id(kettle_mode).state.compare("standby");
        auto mode_call = id(kettle_mode).make_call();

        if (is_kettle_mode_active) {
          mode_call.set_option("standby");
          mode_call.perform();
        } else {
          mode_call.set_option("heat up & hold");
          mode_call.perform();
        }

  - platform: template
    id: button_hold
    on_click:
      lambda: |-
        bool is_kettle_mode_hold = !id(kettle_mode).state.compare("heat up & hold");
        auto mode_call = id(kettle_mode).make_call();

        if (!is_kettle_mode_hold) {
          mode_call.set_option("heat up & hold");
          mode_call.perform();
        } else {
          mode_call.set_option("heat up");
          mode_call.perform();
        }

  - platform: template
    id: button_menu
    on_click:
      lambda: |-
        auto options = id(profile).traits.get_options();
        auto current = id(profile).state;

        auto index = find(options.begin(), options.end(), current);

        index++;

        auto call = id(profile).make_call();
        if (index == options.end())
          call.set_option(*options.begin());
        else
          call.set_option(*index);
        call.perform();

  - platform: template
    id: button_timer

  - platform: template
    id: button_plus
    on_click:
      lambda: |-
        auto pid_call = id(temperature_pid).make_call();
        float current = id(temperature_pid).target_temperature;
        float max_temperature = id(temperature_pid).get_traits().get_visual_max_temperature();
        float next_temperature_step = current + 1.0;
        float new_temperature = min(next_temperature_step, max_temperature);
        pid_call.set_target_temperature(new_temperature);
        pid_call.perform();

  - platform: template
    id: button_minus
    on_click:
      lambda: |-
        auto pid_call = id(temperature_pid).make_call();
        float current = id(temperature_pid).target_temperature;
        float min_temperature = id(temperature_pid).get_traits().get_visual_min_temperature();
        float next_temperature_step = current - 1.0;
        float new_temperature = max(next_temperature_step, min_temperature);
        pid_call.set_target_temperature(new_temperature);
        pid_call.perform();

interval:
  - interval: 333ms
    then:
      if:
        condition:
          for:
            time: 1s
            condition:
              binary_sensor.is_on: button_plus
        then:
          lambda: |-
            auto pid_call = id(temperature_pid).make_call();
            float current = id(temperature_pid).target_temperature;
            float max_temperature = id(temperature_pid).get_traits().get_visual_max_temperature();
            float next_temperature_step = current - ((int)current % 5) + 5.0;
            float new_temperature = min(next_temperature_step, max_temperature);
            pid_call.set_target_temperature(new_temperature);
            pid_call.perform();

  - interval: 333ms
    then:
      if:
        condition:
          for:
            time: 1s
            condition:
              binary_sensor.is_on: button_minus
        then:
          lambda: |-
            auto pid_call = id(temperature_pid).make_call();
            float current = id(temperature_pid).target_temperature;
            float min_temperature = id(temperature_pid).get_traits().get_visual_min_temperature();
            float next_temperature_step = min_temperature;
            if ((int)current % 5) {
              next_temperature_step = current - ((int)current % 5);
            } else {
              next_temperature_step = current - 5.0;
            }
            float new_temperature = max(next_temperature_step, min_temperature);
            pid_call.set_target_temperature(new_temperature);
            pid_call.perform();

button:
  - platform: template
    name: OnOff Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_onoff
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_onoff
            state: false

  - platform: template
    name: OnOff ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_onoff
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_onoff
            state: false

  - platform: template
    name: Hold Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_hold
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_hold
            state: false

  - platform: template
    name: Hold ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_hold
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_hold
            state: false

  - platform: template
    name: Menu Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_menu
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_menu
            state: false

  - platform: template
    name: Menu ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_menu
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_menu
            state: false

  - platform: template
    name: Timer Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_timer
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_timer
            state: false

  - platform: template
    name: Timer ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_timer
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_timer
            state: false

  - platform: template
    name: Plus Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_plus
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_plus
            state: false

  - platform: template
    name: Plus ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_plus
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_plus
            state: false

  - platform: template
    name: Plus ClickHold
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_plus
            state: true
        - delay: 1.7s
        - binary_sensor.template.publish:
            id: button_plus
            state: false

  - platform: template
    name: Minus Click
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_minus
            state: true
        - delay: 150ms
        - binary_sensor.template.publish:
            id: button_minus
            state: false

  - platform: template
    name: Minus ClickLong
    on_press:
      then:
        - binary_sensor.template.publish:
            id: button_minus
            state: true
        - delay: 600ms
        - binary_sensor.template.publish:
            id: button_minus
            state: false

