substitutions:
  profile_coffee_temperature: "96.0"
  profile_coffee_timer: "240.0"
  profile_black_tea_temperature: "90.0"
  profile_black_tea_timer: "200.0"
  profile_green_tea_temperature: "60.0"
  profile_green_tea_timer: "180.0"
  profile_hot_bottle_temperature: "85.0"

globals:
  - id: profile_general_temperature
    type: float
    restore_value: true
    initial_value: "50.0"
  - id: kettle_mode_hold_on_start
    type: bool
    restore_value: true
    initial_value: "true"
  - id: kettle_mode_standby_on_tilt
    type: bool
    restore_value: true
    initial_value: "true"
  - id: timer_toggle_on_tilt
    type: bool
    restore_value: true
    initial_value: "true"

select:
  - platform: template
    id: profile
    name: Profile
    optimistic: true
    update_interval: never
    options:
      - General
      - Coffee
      - Black Tea
      - Liquorice
      - Green Tea
      - Hot Bottle
    on_value:
      then:
        - select.set:
            id: kettle_mode
            option: standby
        - script.execute: timer_stop

        - if:
            condition:
              lambda: return !x.compare("General");
            then:
              - lambda: |-
                  auto call = id(temperature_pid).make_call();
                  call.set_target_temperature(id(profile_general_temperature));
                  call.perform();
              - select.set:
                  id: timer_direction
                  option: Count Up
              - number.set:
                  id: timer_default_value
                  value: 0.0
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "false"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "false"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "true"

        - if:
            condition:
              lambda: return !x.compare("Coffee");
            then:
              - climate.control:
                  id: temperature_pid
                  target_temperature: ${profile_coffee_temperature}
              - select.set:
                  id: timer_direction
                  option: Count Down
              - number.set:
                  id: timer_default_value
                  value: ${profile_coffee_timer}
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "true"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "false"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "true"

        - if:
            condition:
              lambda: return !x.compare("Black Tea");
            then:
              - climate.control:
                  id: temperature_pid
                  target_temperature: ${profile_black_tea_temperature}
              - select.set:
                  id: timer_direction
                  option: Count Down
              - number.set:
                  id: timer_default_value
                  value: ${profile_black_tea_timer}
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "true"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "true"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "true"

        - if:
            condition:
              lambda: return !x.compare("Liquorice");
            then:
              - climate.control:
                  id: temperature_pid
                  target_temperature: 95.0
              - select.set:
                  id: timer_direction
                  option: Count Down
              - number.set:
                  id: timer_default_value
                  value: 600
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "true"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "true"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "true"

        - if:
            condition:
              lambda: return !x.compare("Green Tea");
            then:
              - climate.control:
                  id: temperature_pid
                  target_temperature: ${profile_green_tea_temperature}
              - select.set:
                  id: timer_direction
                  option: Count Down
              - number.set:
                  id: timer_default_value
                  value: ${profile_green_tea_timer}
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "true"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "true"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "true"

        - if:
            condition:
              lambda: return !x.compare("Hot Bottle");
            then:
              - climate.control:
                  id: temperature_pid
                  target_temperature: ${profile_hot_bottle_temperature}
              - select.set:
                  id: timer_direction
                  option: Count Up
              - number.set:
                  id: timer_default_value
                  value: 0.0
              - globals.set:
                  id: kettle_mode_hold_on_start
                  value: "true"
              - globals.set:
                  id: kettle_mode_standby_on_tilt
                  value: "true"
              - globals.set:
                  id: timer_toggle_on_tilt
                  value: "false"

