substitutions:
  min_time_for_run: "15min"

esphome:
  on_boot:
    - then:
      - sensor.template.publish:
          id: runs
          state: !lambda 'return id(global_runs);'

globals:
  id: global_runs
  type: int
  restore_value: true
  initial_value: '0'

binary_sensor:
  - platform: gpio
    name: ${name_verbose} In Station
    pin: GPIO16
  - platform: gpio
    id: running
    pin: GPIO16
    filters:
      - delayed_off: ${min_time_for_run}
    on_release:
      - lambda: |-
          id(global_runs) += 1;
      - sensor.template.publish:
          id: runs
          state: !lambda return id(global_runs);

sensor:
  - platform: template
    id: runs
    name: ${name_verbose} Runs
    icon: mdi:pound
    update_interval: never
    unit_of_measurement: n
    accuracy_decimals: 0
    lambda: return id(global_runs);

