substitutions:
  pin_kettle_button: GPIO19
  pin_kettle_led: GPIO18

binary_sensor:
  - platform: gpio
    id: kettle_button
    name: ${name_verbose} Button
    pin:
      number: ${pin_kettle_button}
      inverted: true
      mode:
        input: true
        pullup: true

light:
  - platform: binary
    id: kettle_led
    name: ${name_verbose} Button LED
    output: kettle_led_output

switch:
  - platform: output
    id: kettle_led_switch
    name: ${name_verbose} Button LED Switch
    output: kettle_led_output
    icon: mdi:led-on

output:
  - platform: gpio
    id: kettle_led_output
    pin: ${pin_kettle_led}
