substitutions:
  pin_kettle_button: GPIO19
  pin_kettle_led: GPIO18

binary_sensor:
  - platform: gpio
    id: kettle_button
    pin:
      number: ${pin_kettle_button}
      inverted: true
      mode:
        input: true
        pullup: true

switch:
  - platform: output
    id: kettle_led_switch
    output: kettle_led_output
    icon: mdi:led-on

output:
  - platform: gpio
    id: kettle_led_output
    pin: ${pin_kettle_led}
