number:
  - platform: template
    name: Fake Water Temperature
    id: fake_temperature
    min_value: 0
    max_value: 101
    step: 1
    optimistic: true
    on_value:
      - lambda: "id(water_temperature).publish_state(x);"

sensor:
  - platform: template
    name: Water Temperature
    id: water_temperature
    update_interval: 5s
    lambda: |-
      return id(fake_temperature).state;
      //return 42.0 + (random_float() - 0.5) * 5.0;
    unit_of_measurement: "°C"
    device_class: "temperature"

  - platform: template
    id: battery_voltage
    name: Battery Voltage
    lambda: !lambda "return 4.0;"
    unit_of_measurement: "V"
    device_class: "voltage"

  - platform: template
    id: battery_level
    name: Battery Level
    lambda: !lambda "return 42.0;"
    unit_of_measurement: "%"
    device_class: "battery"

switch:
  - platform: template
    name: Kettle in Base
    id: kettle_in_base
    optimistic: true

